version: '3.8'

services:
  web:
    build: .
    command: gunicorn nevskie_medvedi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_BASE_PATH=/app/db
      - ENV_MODE=dev
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nevskie_medvedi
      POSTGRES_USER: nevskie_user
      POSTGRES_PASSWORD: secure_password

volumes:
  postgres_data:
