# Generated by Django 5.1.1 on 2024-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_branch_remove_session_coach_client_branches_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]