# Generated by Django 5.1.1 on 2024-10-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_branch_contact_info_branch_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="client.subscription",
            ),
        ),
    ]
