# Generated by Django 5.1.1 on 2024-10-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subscription',
        ),
    ]
