FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

RUN npm run build


FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY package.json ./

RUN npm install --production

EXPOSE 3000

CMD ["node", "dist/main.js"]
