# Generated by Django 5.1.1 on 2024-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0003_trainingsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("working_hours", models.CharField(max_length=100)),
                ("contact_info", models.CharField(max_length=100)),
            ],
        ),
    ]