# Generated by Django 5.1.1 on 2024-10-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
