# Generated by Django 5.1.1 on 2024-10-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_branch_contact_info_branch_working_hours'),
        ('coach', '0005_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='branch',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='client.branch'),
            preserve_default=False,
        ),
    ]
