# Generated by Django 5.1.1 on 2024-10-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_branch_contact_info_branch_working_hours'),
        ('coach', '0006_trainingsession_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='children_list',
            field=models.ManyToManyField(related_name='children_list_training_sessions', to='client.child'),
        ),
    ]
