# Generated by Django 5.1.1 on 2024-10-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_trainingsession_children_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='coach',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
