# Generated by Django 5.1.1 on 2024-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_remove_session_coach_delete_event_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='group_level',
            field=models.CharField(default='Beginner', max_length=100),
            preserve_default=False,
        ),
    ]
